### ISSUE TITLE
Git Push via Https with Credential Stored in Local

### ISSUE THREAD

**Issue by peterhp** [peterhp/HelloJava#1]

**Comment by peterhp** [comment]
While connecting to the remote git server with HTTPS, we can use a credentials system git provided to store our credential permanently or just temporarily.

``` bash
git config --global credential.helper cache   # store credential in memory for a certain period
git config --global credential.helper wincred # store credential permanently in windows
```

**Comment by EthanLin-TWer** [comment]
赞。http://debugtalk.com/post/head-first-git-authority-verification 留一个，文章将Git的权限校验（https/ssh）讲得清清楚楚的，可以推荐一下。
