### ISSUE TITLE
Succeed to Run CI

### ISSUE THREAD

**Issue by peterhp** [peterhp/HelloJava#2]
Maybe the user permission cause its failure.

**Comment by peterhp** [comment]
# Analysis

Run `git ls-tree HEAD`, and we can see `100644 blob xxxxxxxx gradlew`.
It's clear that gradlew stored in git repository has no exe permission.

**Comment by peterhp** [comment]
# Solution 1

First, add exe permission to gradlew file with `git update-index --chmod=+x gradlew`.
Then, commit the change and push the repository onto the remote repository.

**Comment by peterhp** [comment]
# Solution 2

No needs to modify the permissions in git repository, just chmod for gradlew before building.
So add the following option to .travis.yml file, and it will run ok.

``` bash
before_install:
 - chmod +x gradlew
```

**Comment by EthanLin-TWer** [comment]
my gradlew runs just fine in travis-ci so no idea what's going on but it's right that the problem is caused by lacking of execution permissions of `./gradlew`
